apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airun-aks-ingress
  namespace: default
  labels:
    app: airun
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-path: "/healthz"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399"
    appgw.ingress.kubernetes.io/request-timeout: "60"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airun-service
                port:
                  number: 80
