apiVersion: v2
name: airun-data-plane
description: Production Helm chart for airun Real-Time Rust Data Plane & GPU DaemonSet on GKE/EKS
type: application
version: 0.1.3
appVersion: "0.1.3"
keywords:
  - ai-infrastructure
  - gpu-telemetry
  - dcgm
  - finops
  - economics
maintainers:
  - name: airun Team
    email: infra@airun.dev
